#!/usr/bin/env python3

import jwt
import sys

# Test token from the frontend error
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODUwMzlkNDczMjc4Mjg5ZmQwOTUwNmIiLCJpYXQiOjE3NTAyMzI5MzksInR5cGUiOiJhY2Nlc3MiLCJleHAiOjE3NTA4Mzc3Mzl9.sKd9WrMaLNk42tRBD55xgxoNXUkq-6Z1ifmh8Fsq97Q"

# List of possible JWT secrets
secrets = [
    "bHN0E&CfePq^^EYu1tD5FAoVRO*M46Dj9uhqQxuriilf@7Dy3A3a#LEFotx*69ML",  # Current config secret
    "your-jwt-secret-key-change-in-production-mongodb-auth",  # Default secret
    "your-secret-key",  # Simple default
    "secret",  # Very simple
    "your-jwt-secret-key",  # Common default
]

print("Testing JWT Token with Different Secrets")
print("="*50)

for i, secret in enumerate(secrets):
    try:
        payload = jwt.decode(token, secret, algorithms=["HS256"])
        print(f"✅ SECRET {i+1} WORKS: '{secret[:50]}...'")
        print(f"   Decoded payload: {payload}")
        break
    except jwt.InvalidSignatureError:
        print(f"❌ SECRET {i+1} FAILED: '{secret[:50]}...'")
    except Exception as e:
        print(f"❌ SECRET {i+1} ERROR: {e}")

print("\nIf none of the secrets work, the token might be:")
print("1. Generated with a different secret")
print("2. Generated by a different service")
print("3. Corrupted during transmission")